image: alpine:latest
stages:
- .pre
- build
- test
- release
- .post

before_script:
- apk update
- apk add --no-cache libxml2-utils zip

build:
  artifacts:
    paths:
    - Abaddon.taco
    reports:
      dotenv: gitlab-ci.env
  script:
  - echo  "BUILD_JOB_ID=${CI_JOB_ID}" > gitlab-ci.env
  - zip -r -9 Abaddon.taco *.xml Img
  stage: build

test:
  script:
  - |
    for i in *.xml; do
      xmllint --output "${i}" --noblanks --encode "utf-8" "${i}" || exit ${?}
    done
  stage: test

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
  - job: build
    artifacts: true
  release:
    name: Release $CI_COMMIT_TAG
    description: Abaddon's TacO - Release $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
    ref: $CI_COMMIT_TAG
    assets:
      links:
      - name: 'TacO Markers'
        url: 'https://gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/-/jobs/${BUILD_JOB_ID}/artifacts/file/Abaddon.taco'
  rules:
  - if: $CI_COMMIT_TAG
  script:
  - echo "Releasing $CI_COMMIT_TAG from build $BUILD_JOB_ID"
  stage: release

# vim: fileencoding=utf-8 filetype=yaml autoindent expandtab shiftwidth=2 softtabstop=2 tabstop=2 nowrap